name: GitHub Actions Demo
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print the triggering event
        run: echo "The job was triggered by ${{ github.event_name }}."
        
        
        
        
        
       
        
